"""add FK table

Revision ID: 1b6c36c15bb8
Revises: 44e83aa0bbc8
Create Date: 2023-04-05 12:07:14.322388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b6c36c15bb8'
down_revision = '44e83aa0bbc8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sportsman', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sportsman', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sportsman', type_='foreignkey')
    op.drop_column('sportsman', 'team_id')
    # ### end Alembic commands ###
